name: CI/CD

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    env:
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build with Gradle
        id: build
        run: |
          ./gradlew createIliDataXml   
          ls -la

      - name: Build and start Docker container
        run: ./gradlew buildImage startContainer 
        if: ${{ success() }}

      - name: Test repository
        id: usabilityhubcheck
        run: ./gradlew checkUsabilityHub 
        if: ${{ success() }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT }}

      - name: Multi-platform build and push
        run: ./gradlew buildAndPushImages
        if: ${{ (github.ref == 'refs/heads/main') && (github.event_name != 'pull_request') && !env.ACT && (steps.usabilityhubcheck.outcome == 'success')}}